---
lax-cor-r1:
  hostname: '172.16.1.100'
  port: 22
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_nxos'

lax-edg-r1:
  hostname: '172.16.1.10'
  port: 22
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'


lax-edg-r2:
  hostname: '172.16.1.11'
  port: 22
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'


